#docker-compose build --no-cache 
version: "3"
services:
  nginx:
    image: nginx
    container_name: cda_projet2_nginx
    init: true
    links:
      - php
    volumes:
      - ./Code/:/var/www/html/:ro
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - ${NGINX_PORT}:80

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cda_projet2_php
    volumes:
      - ./Code/:/var/www/html/
    tmpfs: /tmp
    depends_on:
      - mariadb
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: cda_projet2_mariadb
    volumes:
      - ./dump/cda_pt2.sql:/docker-entrypoint-initdb.d/cda_pt2.sql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PW}

  phpmyadmin:
    image: phpmyadmin
    container_name: cda_projet2_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mariadb:db
    environment:
      - UPLOAD_LIMIT=4800000000000
